name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below
        to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure module with...
        2. Run terraform apply...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Terraform Configuration
      description: The relevant Terraform configuration (redact sensitive values)
      render: hcl
      placeholder: |
        module "pypiserver" {
          source  = "infrahouse/pypiserver/aws"
          version = "x.x.x"
          # ...
        }
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: The full error message or unexpected output
      render: shell
      placeholder: Paste the error message here...

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: Version of terraform-aws-pypiserver
      placeholder: "2.1.0"
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Output of `terraform version`
      placeholder: "1.9.0"
    validations:
      required: true

  - type: input
    id: aws-provider-version
    attributes:
      label: AWS Provider Version
      description: Version of hashicorp/aws provider
      placeholder: "5.62.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, logs, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the [troubleshooting guide](https://infrahouse.github.io/terraform-aws-pypiserver/troubleshooting/)
          required: true
