name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see added to
        the module.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like the module to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how this could be implemented, share them
      placeholder: |
        This could be implemented by:
        - Adding a new variable...
        - Modifying the ECS configuration...

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would this feature benefit users?
      options:
        - High - Enables new use cases
        - Medium - Improves existing functionality
        - Low - Nice to have
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
